export const ADD_NOTE = 'ADD_NNTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const SET_ACTIVE_NOTE = 'SET_ACTIVE_NOTE'
